### ISSUE TITLE
Pr was Not Right

### ISSUE THREAD

**Issue by TheBaconSpace** [WatchBeam/beam-branding-kit#6]
@ttaylorr Twitter account.
 i thought i Changed it would u Be able to change it if that was the thing u wanted done or no?

**Comment by ttaylorr** [comment]
Hi, @TheBaconSpace - your PR was fine, and merged correctly! The latest ref on master (739a5354c9b68cb7fc7b8c9b84e26f22f8c045c9) shows that the link to our Twitter in the [README](https://raw.githubusercontent.com/WatchBeam/beam-branding-kit/739a5354c9b68cb7fc7b8c9b84e26f22f8c045c9/readme.md) is `https://twitter.com/Beam`, which is correctly styled.

I'm going to close this since everything is fine, but please let me know if you have any other questions!
